# Block where generation will happen above
base_block: "barrier"

# Generation interval in seconds
generation_interval: 1.5

# Radius around player to check for generation
generation_radius: 25

# Blocks to generate (can be ores or any other blocks)
generated_blocks:
  - "iron_ore"
  - "diamond_ore"
  - "coal_ore"
  - "emerald_ore"
  - "gold_ore"